---
# curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
- name: Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

# add-apt-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
# At the time of writing, Ubuntu 18.04 (Bionic) packages for Kubernetes are not available.
# Check here https://packages.cloud.google.com/apt/dists
- name: Set up Kubernetes repository
  apt_repository: repo='deb http://apt.kubernetes.io/ kubernetes-xenial main' state=present

# apt update; apt install -y kubelet=1.11.1-00 kubectl=1.11.1-00 kubeadm=1.11.1-00
- name: Install kube CLIs
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet={{ k8s_version }}-00
      - kubectl={{ k8s_version }}-00
      - kubeadm={{ k8s_version }}-00

# - import_tasks: install_kube_prompt_tasks.yml
