---
k8s_version: "v1.10.4"
calico_yaml: https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

auth_url: http://192.168.121.15/identity/v3/
user_id: 3fd32295751a41aca601021eba681a29
password: password
tenant_id: 84ce53873abe4d22a6f2491879e76048
region: RegionOne
subnet_id: 1740cd57-62ab-4f7f-a853-2038561060d1
